### ISSUE TITLE
Mobile auto collapse issue

### ISSUE THREAD

**Issue by melroy89** [dharmapoudel/jQueryTab#2]
Hi,

When I tried the index.html demo page, I noticed a bug. 

I clicked on the menu item, it will expend, however directly after that the content will collapse automatically. This is only with the mobile version.

I think it have something to the with the effects.

It effects: Demo #1, #6 & #7.

Kind regards,
Melroy

**Comment by dharmapoudel** [comment]
@danger89 I was trying to add the keyboard navigation to the plugin recently. Looks like the parameter 'keyboardNavigation: true' seems to be causing trouble. I'll fix it asap.

**Comment by dharmapoudel** [comment]
This issue should be fixed.

**Comment by melroy89** [comment]
ok thx!
